household_power_consumption <- read.csv("household_power_consumption.txt", header=TRUE, sep=";")
head(household_power_consumption)
data <- subset(household_power_consumption, Date == "1/2/2007" | Date == "2/2/2007")
install.packages("lubridate")
library(lubridate)
data$datetime <- dmy_hms(paste(data$Date , data$Time))
data$Global_active_power <- as.numeric(as.character(data$Global_active_power))
par(mfrow = c(1,1))
plot(data$datetime,data$Global_active_power ,"lines" ,  xlab = "" , ylab = "Global Active Power (kilowatts)" )
dev.copy(png,filename = "plot2.png" , width = 480 , height = 480)
dev.off()
