household_power_consumption <- read.csv("household_power_consumption.txt", header=TRUE, sep=";")
head(household_power_consumption)
data <- subset(household_power_consumption, Date == "1/2/2007" | Date == "2/2/2007")
install.packages("lubridate")
library(lubridate)
data$datetime <- dmy_hms(paste(data$Date , data$Time))
data$Global_active_power <- as.numeric(as.character(data$Global_active_power))
data$Global_reactive_power <- as.numeric(as.character(data$Global_reactive_power))
data$Voltage <- as.numeric(as.character(data$Voltage))
data$Sub_metering_1 <- as.numeric(as.character(data$Sub_metering_1))
data$Sub_metering_2 <- as.numeric(as.character(data$Sub_metering_2))
data$Sub_metering_3 <- as.numeric(as.character(data$Sub_metering_3))
par(mfrow=c(2,2))
plot(data$datetime,data$Global_active_power ,"lines" ,  xlab = "" , ylab = "Global Active Power " )
plot(data$datetime , data$Voltage , "lines" , xlab ="datetime" ,ylab ="Voltage" )
plot(data$datetime ,data$Sub_metering_1 , "lines" , xlab = "" , ylab = "Energy sub metering")
lines(data$datetime ,data$Sub_metering_2 , col = "orange")
lines(data$datetime ,data$Sub_metering_3 , col = "blue")
legend("topright" , legend = c("Sub_metering_1", "Sub_metering_2" , "Sub_metering_3") ,bty = 'n',
       lty = c(1,1,1),lwd=1, col =c("black" ,"orange" ,"blue"), adj = 0.15, y.intersp = 0.4 ,cex = 0.5)
plot(data$datetime ,  data$Global_reactive_power ,"lines", xlab = "datetime" , ylab = "Global_reactive_Power" )
dev.copy(png,filename = "plot4.png" , width = 480 , height = 480)
dev.off()

